### ISSUE TITLE
Breadcrumbs don't match URL. 

### ISSUE THREAD

**Issue by ayaleloehr** [department-of-veterans-affairs/gi-bill-comparison-tool#276]
The breadcrumbs on the GI Bill Comparison Tool main page are "Education Benefits > GI Bill > GI Bill Comparison Tool", but the URL is just "vets.gov/gi-bill-comparison-tool" (image below).  To match the rest of the site, either the URL would change to "vets.gov/education-benefits/gi-bill/gi-bill-comparison-tool" or the breadcrumb would change to just "GI Bill Comparison Tool".  Do we want to change one of these?

<img width="1204" alt="screen shot 2016-02-13 at 4 06 00 pm" src="https://cloud.githubusercontent.com/assets/4719765/13030069/11f42446-d26c-11e5-8de6-cf756a248bac.png">

**Comment by rickleegit** [comment]
This is a good question and an interesting observation. Historically, the tool has been a stand alone. In the architecture of the site, as it exists now, it lives in two slots within the IA of the vets.gov - at root > L1 in the footer and at root > L1 > L2 within education benefits. 

Because of the number of external links that point directly to the CT (over 2000), and the large number of sessions that the CT registers, my recommendation would be to leave the link as is. Additionally, I am not really sure that, although the URL is technically incorrect, there is appreciable awareness or impact on the user in this case. The breadcrumb, though not aligned with the URL, adds context.

**Comment by saintsoup52** [comment]
While I prefer leaving the breadcrumbs as they are... 

I have to +1 the request to not change the url... we just got lots of people to make the switch to the new URL and I don't want to have to go back to them again. Plus I think the simpler URL for a tool like this makes more sense.
